### ISSUE TITLE
Always allocate a new value

### ISSUE THREAD

**Issue by Miles-Garnsey** [adutra/goalesce#10]
There is a comment [here](https://github.com/adutra/goalesce/blob/main/coalesce.go#L36):

> // The function never modifies its inputs. It may return one of the (unmodified) inputs as the coalesced value, but
> // whenever changes to the inputs are required, the function always returns an entirely newly-allocated value.

Can I ask that we change the logic here so that a newly allocated value is always returned? I have some concerns about the fact that the behaviour is inconsistent between when a value is changed vs when it isn't. 

It makes it hard to reason about whether a returned value that is then mutated outside the Goalesce logic is actually mutating the original object or not (as this would differ depending on whether the object was changed by Goalesce). 

This class of errors will also be hard to catch in tests.

**Comment by adutra** [comment]
In fact, we might not have a huge problem here. Given its signature, the `Coalesce` function always returns a copy of the coalesced object. 

The only issue will be with pointers. When coalescing pointers, a copy of the coalesced pointer is returned. If that returned pointer happens to be v1 or v2, it would point to the same address. Which means that modifying the coalesced pointer will affect the inputs.

This is captured by the following test, which currently fails:

```go
func TestCopy(t *testing.T) {
	v1 := intPtr(1)
	got, err := Coalesce(v1, nil)
	assert.NoError(t, err)
	assert.Equal(t, intPtr(1), got)
	assert.Equal(t, intPtr(1), v1)
	*got.(*int) = 2
	assert.Equal(t, intPtr(2), got)
	assert.Equal(t, intPtr(1), v1) // fails, v1 = 2
}
```

So yes, I'm 👍 to implement this.

**Comment by adutra** [comment]
The problem might also happen for slices and maps as well, in fact.

**Comment by adutra** [comment]
I've been playing with your idea today @Miles-Garnsey . In fact, this will lead to the creation of a deep-copy function, because the copy cannot be just a shallow one, it has to copy the entire object graph.

I still think this is a valid ask, but it might lead to repurpose the library: why not expose the deep-copy function as well? In this case Goalesce would propose both a (deep) copy and a (deep) merge functionality.

**Comment by Miles-Garnsey** [comment]
A lot to cover here so pardon the headings...

## In place vs new value

I'm open minded on which one is optimal, as long as the return is consistently either a new value or nil return with v1 mutated in place (definitely more memory efficient, I agree). I'd advocate that we pick whichever is easiest and implement it first.

As a second step, ideally we might have both available for users and controlled by an option.

If we are going to implement a `DeepCopy` function as a consequence of implementing other logic, then by all means let's expose it. I think the core logic between `Coalesce` and `DeepCopy` functions is similar, but `DeepCopy` might need to handle cycles differently.

## Can we factor out the reflective logic?

If we do end up with three types of functions (in-place, new value, and DeepCopy), one question is whether it is possible/useful to have a higher order function `.DualTraverse` with signature `func DualTraverse(v1, v2 reflect.Value, f func(v1, v2 reflect.Value) reflect.Value`.

We could then build the DeepCopy/Coalesce logic on top of that so that we can factor out all of the reflective logic for further re-use. This is just a thought bubble, so feel free to tell me if it is silly, HOFs can become hard in Go, but given the input/output types are all `reflect.Value` this might be a rare case where it works.

**Comment by adutra** [comment]
> I'm open minded on which one is optimal, as long as the return is consistently either a new value or nil return with v1 mutated in place (definitely more memory efficient, I agree). I'd advocate that we pick whichever is easiest and implement it first.

Allocating new values is way easier. I will start with that and leave in-place for later, if we ever implement it.

> As a second step, ideally we might have both available for users and controlled by an option.

I'd rather have two different top-level functions: `Coalesce` for new values, and, say, `Merge` for in-place. The signatures are not quite the same: the latter doesn't return any value while, while the former does.

Yeah, that's an interesting idea. It would only apply for in-place and new-value though, as DeepCopy is unary (it only takes one value, not two).
